name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true

      - run: npm --workspaces i
      - run: npm --workspaces --if-present run build
      - run: npm --workspaces --if-present run test
